version: "3"
name: sd
# Changes the project's name:
services:
  mongo:
    image: mongo
    container_name: mongodb
    volumes:
      - sd:/home/node/app
    # persist data
    networks:
      - sd-project

  service-a: # This will be the container's network alias
    build:
      context: .
      dockerfile: docker/service-a.Dockerfile
    ports:
      - "7000:5000"
      # host_port:container_port
      # I'm currently making every call to localhost:7000
      # to be redirected to container:5000 (default flask port)
    networks:
      - sd-project

  service-b:
    build:
      context: .
      dockerfile: docker/service-b.Dockerfile
    ports:
      - "7001:5000"
    networks:
      - sd-project
networks:
  # The presence of these objects is sufficient to define them
  sd-project: {}
volumes:
  sd:
